/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package foodcity;

import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author kavinduakash
 */
public class CustomerPanel extends javax.swing.JPanel {

    /** Creates new form CustomerPanel */
    public CustomerPanel() {
        initComponents();
        loadCustomerTbl();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        customerIdTextField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        customerNameTextField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        customerEmailTextField = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        customerAddressTextField = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        customerSaveBtn = new javax.swing.JButton();
        customerUpdateBtn = new javax.swing.JButton();
        customerDeleteBtn = new javax.swing.JButton();
        customerResetBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 153, 153));
        setPreferredSize(new java.awt.Dimension(800, 550));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 50));

        jLabel1.setFont(new java.awt.Font("Muna", 1, 24)); // NOI18N
        jLabel1.setText("Customer Management");
        jPanel1.add(jLabel1);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 46));
        jPanel3.setLayout(new java.awt.GridLayout(2, 0));

        jLabel2.setText("ID");
        jPanel3.add(jLabel2);

        customerIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIdTextFieldActionPerformed(evt);
            }
        });
        jPanel3.add(customerIdTextField);

        jPanel6.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridLayout(2, 0));

        jLabel3.setText("Name");
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 17));
        jPanel4.add(jLabel3);

        customerNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameTextFieldActionPerformed(evt);
            }
        });
        jPanel4.add(customerNameTextField);

        jPanel6.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridLayout(2, 0));

        jLabel4.setText("Email");
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 17));
        jPanel5.add(jLabel4);

        customerEmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerEmailTextFieldActionPerformed(evt);
            }
        });
        jPanel5.add(customerEmailTextField);

        jPanel6.add(jPanel5);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.GridLayout(2, 0));

        jLabel5.setText("Address");
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 17));
        jPanel7.add(jLabel5);

        customerAddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerAddressTextFieldActionPerformed(evt);
            }
        });
        jPanel7.add(customerAddressTextField);

        jPanel6.add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        customerSaveBtn.setBackground(new java.awt.Color(153, 255, 153));
        customerSaveBtn.setText("Save");
        customerSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerSaveBtnActionPerformed(evt);
            }
        });
        jPanel8.add(customerSaveBtn);

        customerUpdateBtn.setBackground(new java.awt.Color(153, 204, 255));
        customerUpdateBtn.setText("Update");
        customerUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerUpdateBtnActionPerformed(evt);
            }
        });
        jPanel8.add(customerUpdateBtn);

        customerDeleteBtn.setBackground(new java.awt.Color(255, 153, 153));
        customerDeleteBtn.setText("Delete");
        jPanel8.add(customerDeleteBtn);

        customerResetBtn.setBackground(new java.awt.Color(255, 255, 51));
        customerResetBtn.setText("Reset");
        jPanel8.add(customerResetBtn);

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Email", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        customerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(customerTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void customerIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerIdTextFieldActionPerformed

    private void customerAddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerAddressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerAddressTextFieldActionPerformed

    private void customerEmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerEmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerEmailTextFieldActionPerformed

    private void customerNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameTextFieldActionPerformed

    private void customerSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerSaveBtnActionPerformed
        // TODO add your handling code here: 
        String id = customerIdTextField.getText();
        String name = customerNameTextField.getText();
        String email = customerEmailTextField.getText();
        String address = customerAddressTextField.getText();
        
        String DB_URL = "jdbc:mysql://localhost:3306/supermarket";
        String DB_USER = "root";
        String DB_PASSWORD = "ijse";
        
        try {
        
            Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
            
            if(conn!=null) {
                System.out.println("Connected!!!");
                
                String sql = "INSERT INTO customers(id, name, email, address) VALUES (" + id + ", '" + name + "', '"+ email +"', '" + address + "')";
            
                Statement stm = conn.createStatement();
                
                int result = stm.executeUpdate(sql);
                
                if(result > 0) {
                    JOptionPane.showMessageDialog(null, "Customer Saved Successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                    loadCustomerTbl();
                    cleanCustomerTextFileds();
                }
            }
            
        } catch(Exception e) {
            System.out.println("Something went wrong!!!");
        }
       
    }//GEN-LAST:event_customerSaveBtnActionPerformed

    private void customerUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerUpdateBtnActionPerformed
        // TODO add your handling code here:
        String id = customerIdTextField.getText();
        String name = customerNameTextField.getText();
        String email = customerEmailTextField.getText();
        String address = customerAddressTextField.getText();
        
        String DB_URL = "jdbc:mysql://localhost:3306/supermarket";
        String DB_USER = "root";
        String DB_PASSWORD = "ijse";
        
        try {
        
            Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
            
            if(conn!=null) {
                System.out.println("Connected!!!");
                
                String sql = "UPDATE customers SET name='" + name + "', email='" + email + "', address='" + address + "' WHERE id=" + id;
            
                Statement stm = conn.createStatement();
                
                int result = stm.executeUpdate(sql);
                
                if(result > 0) {
                    JOptionPane.showMessageDialog(null, "Customer Updated Successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                    loadCustomerTbl();
                    cleanCustomerTextFileds();
                }
            }
            
        } catch(Exception e) {
            System.out.println("Something went wrong!!!");
        }
    }//GEN-LAST:event_customerUpdateBtnActionPerformed

    private void customerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerTableMouseClicked
        // TODO add your handling code here:
        
        int row = customerTable.getSelectedRow();
        System.out.println(row);
        
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel)customerTable.getModel();
        
        String id = model.getValueAt(row, 0).toString();
        String name = model.getValueAt(row, 1).toString();
        String email = model.getValueAt(row, 2).toString();
        String address = model.getValueAt(row, 3).toString();
        
        System.out.println(id + ", " + name + ",  " + email + ", " + address);
        
        customerIdTextField.setText(id);
        customerNameTextField.setText(name);
        customerEmailTextField.setText(email);
        customerAddressTextField.setText(address);
    }//GEN-LAST:event_customerTableMouseClicked

    private void loadCustomerTbl() {
        
        String DB_URL = "jdbc:mysql://localhost:3306/supermarket";
        String DB_USER = "root";
        String DB_PASSWORD = "ijse";
        
        try {
            Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
            
            if(conn!=null) {
                
                String sql = "SELECT * FROM customers";
                
                Statement stm = conn.createStatement();
                
                ResultSet result = stm.executeQuery(sql);
                
                javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel)customerTable.getModel();
                
                model.setRowCount(0);
            
                while(result.next()) {
                    int id = result.getInt("id");
                    String name = result.getString("name");
                    String email = result.getString("email");
                    String address = result.getString("address");
                    
                    System.out.println(id + ", " + name + ", " + email + ", " + address);
                    
                    Object[] new_row = new Object[]{id, name, email, address};
                    model.addRow(new_row);
                }
                
            }
            
        } catch(Exception e) {
            System.out.println("Something went wrong!!!");
        }
    }
    
    private void cleanCustomerTextFileds() {
        customerIdTextField.setText("");
        customerNameTextField.setText("");
        customerEmailTextField.setText("");
        customerAddressTextField.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField customerAddressTextField;
    private javax.swing.JButton customerDeleteBtn;
    private javax.swing.JTextField customerEmailTextField;
    private javax.swing.JTextField customerIdTextField;
    private javax.swing.JTextField customerNameTextField;
    private javax.swing.JButton customerResetBtn;
    private javax.swing.JButton customerSaveBtn;
    private javax.swing.JTable customerTable;
    private javax.swing.JButton customerUpdateBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
