/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package foodcity;

import foodcity.controller.CustomerController;
import foodcity.controller.ItemController;
import foodcity.controller.OrderController;
import foodcity.dto.CustomerDTO;
import foodcity.dto.OrderItemDTO;
import foodcity.dto.ItemDTO;
import foodcity.dto.OrderDTO;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author kavinduakash
 */
public class OrderPanel extends javax.swing.JPanel {

    private final CustomerController customerController = new CustomerController();
    private final ItemController itemController = new ItemController();
    private final OrderController orderController = new OrderController();
    
    private double total = 0.0;
    
    /**
     * Creates new form CustomerPanel
     */
    public OrderPanel() {
        initComponents();
        loadCustomerComboBox();
        loadItemComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderCartTbl = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        addToCartBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        customerComboBox = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        itemComboBox = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        availableQtyTextField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        qtyTextFiled = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        totalLbl = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        orderResetBtn = new javax.swing.JButton();
        placeOrderBtn = new javax.swing.JButton();

        jLabel4.setText("Email");

        jTextField3.setText("jTextField1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setBackground(new java.awt.Color(204, 255, 51));
        setSize(new java.awt.Dimension(100, 100));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(759, 50));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Order Management");
        jPanel1.add(jLabel1);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        orderCartTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Item", "Qty", "Unit Price", "Total Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(orderCartTbl);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        addToCartBtn.setBackground(new java.awt.Color(204, 255, 204));
        addToCartBtn.setText("Add");
        addToCartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartBtnActionPerformed(evt);
            }
        });
        jPanel7.add(addToCartBtn);

        resetBtn.setBackground(new java.awt.Color(255, 255, 153));
        resetBtn.setText("Reset");
        jPanel7.add(resetBtn);

        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(2, 1));

        jLabel3.setText("Customer");
        jPanel3.add(jLabel3);

        customerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        customerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerComboBoxActionPerformed(evt);
            }
        });
        jPanel3.add(customerComboBox);

        jPanel8.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridLayout(2, 1));

        jLabel5.setText("Item");
        jPanel4.add(jLabel5);

        itemComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        itemComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemComboBoxActionPerformed(evt);
            }
        });
        jPanel4.add(itemComboBox);

        jPanel8.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridLayout(2, 1));

        jLabel2.setText("Available Qty");
        jPanel5.add(jLabel2);

        availableQtyTextField.setEditable(false);
        availableQtyTextField.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel5.add(availableQtyTextField);

        jPanel8.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.GridLayout(2, 1));

        jLabel6.setText("Price");
        jPanel6.add(jLabel6);

        priceTextField.setEditable(false);
        priceTextField.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel6.add(priceTextField);

        jPanel8.add(jPanel6);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.GridLayout(2, 1));

        jLabel7.setText("Qty");
        jPanel9.add(jLabel7);

        qtyTextFiled.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel9.add(qtyTextFiled);

        jPanel8.add(jPanel9);

        jPanel10.setLayout(new java.awt.GridLayout(1, 0));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel8.setText("Total:");
        jPanel10.add(jLabel8);

        totalLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        totalLbl.setForeground(new java.awt.Color(0, 0, 204));
        totalLbl.setText("0.0");
        jPanel10.add(totalLbl);

        jPanel11.setLayout(new java.awt.GridLayout(1, 0));

        orderResetBtn.setBackground(new java.awt.Color(255, 255, 102));
        orderResetBtn.setText("Reset");
        jPanel11.add(orderResetBtn);

        placeOrderBtn.setBackground(new java.awt.Color(102, 153, 255));
        placeOrderBtn.setText("Place Order");
        placeOrderBtn.setPreferredSize(new java.awt.Dimension(99, 80));
        placeOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderBtnActionPerformed(evt);
            }
        });
        jPanel11.add(placeOrderBtn);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void addToCartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartBtnActionPerformed
        // TODO add your handling code here:
        String selectedItemid = (String)itemComboBox.getSelectedItem();
        String qty = qtyTextFiled.getText();
        
        ItemDTO dto = itemController.getItemDetails(Integer.parseInt(selectedItemid));
        
        if(!qty.equals("") && Integer.parseInt(qty)<=dto.getQty() && Integer.parseInt(qty) != 0) {
                double totalItemValue = Integer.parseInt(qty) * dto.getPrice();
                total+=totalItemValue;

                javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel)orderCartTbl.getModel(); 

                Object[] new_row = new Object[]{dto.getId(), dto.getName(), qty, dto.getPrice(), totalItemValue};
                model.addRow(new_row);

                totalLbl.setText(Double.toString(total));

                cleanForm();
        } else {
            JOptionPane.showMessageDialog(null, "Invalid Qty!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addToCartBtnActionPerformed

    private void placeOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderBtnActionPerformed
        // TODO add your handling code here:
        try {
            String customerId = (String)customerComboBox.getSelectedItem();

            int rowCount = orderCartTbl.getRowCount();

            List<OrderItemDTO> oidtoList = new ArrayList<>();

            for(int i=0; i<rowCount; i++) {
                int itemId = (Integer)orderCartTbl.getValueAt(i, 0);
                int qty = (Integer)orderCartTbl.getValueAt(i, 2);
                double unitPrice = (Double)orderCartTbl.getValueAt(i, 3);

                OrderItemDTO oidto = new OrderItemDTO(itemId, qty, unitPrice);
                oidtoList.add(oidto);
            }       

            OrderDTO orderDTO = new OrderDTO(Integer.parseInt(customerId), oidtoList);

            boolean result = orderController.placeOrder(orderDTO);

            if(result) {
                JOptionPane.showMessageDialog(null, "Order Placed Successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                cleanUI();
            } else {
                JOptionPane.showMessageDialog(null, "Something went wrong!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Something went wrong!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_placeOrderBtnActionPerformed

    private void customerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerComboBoxActionPerformed

        String id = (String)customerComboBox.getSelectedItem();        
    }//GEN-LAST:event_customerComboBoxActionPerformed

    private void itemComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemComboBoxActionPerformed
        
        String id = (String)itemComboBox.getSelectedItem();
        System.out.println(id); // null
        
        if(id != null) {
            if(!id.equals("NAN")) {
                ItemDTO dto = itemController.getItemDetails(Integer.parseInt(id));
                int qty = dto.getQty();
                double price = dto.getPrice();
                
                availableQtyTextField.setText(Integer.toString(qty));
                priceTextField.setText(Double.toString(price));
            }
        }        
        
    }//GEN-LAST:event_itemComboBoxActionPerformed

    private void loadCustomerComboBox() {
        List<CustomerDTO> dtos = customerController.getCustomers();
        
        customerComboBox.removeAllItems();
        
        customerComboBox.addItem("NAN");
        
        for(CustomerDTO dto : dtos) {
            int id = dto.getId();
            customerComboBox.addItem(Integer.toString(id));
        }
    }
    
    private void loadItemComboBox() {
        List<ItemDTO> dtos = itemController.getItems();
        
        itemComboBox.removeAllItems();
        
        itemComboBox.addItem("NAN");
        
        for(ItemDTO dto : dtos) {
            int id = dto.getId();
            itemComboBox.addItem(Integer.toString(id));
        }
    }
    
    private void cleanUI() {
        availableQtyTextField.setText("");
        priceTextField.setText("");
        qtyTextFiled.setText("");
        itemComboBox.setSelectedIndex(0); 
        customerComboBox.setSelectedIndex(0); 
        
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel)orderCartTbl.getModel(); 
        model.setRowCount(0);
        
        total = 0.0;
    }
    
    private void cleanForm() {
        availableQtyTextField.setText("");
        priceTextField.setText("");
        qtyTextFiled.setText("");
        itemComboBox.setSelectedIndex(0);   
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCartBtn;
    private javax.swing.JTextField availableQtyTextField;
    private javax.swing.JComboBox<String> customerComboBox;
    private javax.swing.JComboBox<String> itemComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable orderCartTbl;
    private javax.swing.JButton orderResetBtn;
    private javax.swing.JButton placeOrderBtn;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JTextField qtyTextFiled;
    private javax.swing.JButton resetBtn;
    private javax.swing.JLabel totalLbl;
    // End of variables declaration//GEN-END:variables
}
