/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package foodcity;

/**
 *
 * @author kavinduakash
 */
public class PointOfSale extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PointOfSale.class.getName());

    /**
     * Creates new form PointOfSale
     */
    public PointOfSale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarPanel = new javax.swing.JPanel();
        itemTabBtn = new javax.swing.JButton();
        orderTabBtn = new javax.swing.JButton();
        customerTabBtn = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebarPanel.setBackground(new java.awt.Color(153, 255, 153));

        itemTabBtn.setText("Items");
        itemTabBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTabBtnClick(evt);
            }
        });

        orderTabBtn.setText("Orders");
        orderTabBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderTabBtnClick(evt);
            }
        });

        customerTabBtn.setText("Customers");
        customerTabBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerTabBtnClick(evt);
            }
        });

        titleLbl.setFont(new java.awt.Font("Impact", 1, 18)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(153, 0, 153));
        titleLbl.setText("Food City");

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemTabBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orderTabBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerTabBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(titleLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(titleLbl)
                .addGap(26, 26, 26)
                .addComponent(customerTabBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemTabBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderTabBtn)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        getContentPane().add(sidebarPanel, java.awt.BorderLayout.LINE_START);

        mainPanel.setBackground(new java.awt.Color(204, 255, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(800, 550));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orderTabBtnClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderTabBtnClick
        // TODO add your handling code here:
        System.out.println("Clicked Order Tab...");
        
        javax.swing.JPanel orderPanel = new OrderPanel();
        
        mainPanel.setLayout(new java.awt.BorderLayout());
        
        mainPanel.removeAll();
        mainPanel.add(orderPanel, java.awt.BorderLayout.CENTER);
        mainPanel.revalidate();
        mainPanel.repaint();
    }//GEN-LAST:event_orderTabBtnClick

    private void customerTabBtnClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerTabBtnClick
        // TODO add your handling code here:
        System.out.println("Clicked Customer Tab...");
        
        javax.swing.JPanel customerPanel = new CustomerPanel();
        
        mainPanel.setLayout(new java.awt.BorderLayout());
        
        mainPanel.removeAll();
        mainPanel.add(customerPanel, java.awt.BorderLayout.CENTER);
        mainPanel.revalidate();
        mainPanel.repaint();
    }//GEN-LAST:event_customerTabBtnClick

    private void itemTabBtnClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTabBtnClick
        // TODO add your handling code here:
        System.out.println("Clicked Item Tab...");
        
        javax.swing.JPanel itemPanel = new ItemPanel();
        
        mainPanel.setLayout(new java.awt.BorderLayout());
        
        mainPanel.removeAll();
        mainPanel.add(itemPanel, java.awt.BorderLayout.CENTER);
        mainPanel.revalidate();
        mainPanel.repaint();
    }//GEN-LAST:event_itemTabBtnClick

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PointOfSale().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customerTabBtn;
    private javax.swing.JButton itemTabBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton orderTabBtn;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
